### ISSUE TITLE
Incremental improvements to Thyra icon tray

### ISSUE THREAD

**Issue by SlnPons** [massalabs/Thyra-Menu-Bar-App#18]
**Context**
We can improve how Thyra icon tray looks like with simple buy efficient improvements. Such as: 
*toggle to turn on and off Thyra 
* Small menus to separate thyra pages from plug-in pages

**User flow**
1. User goes on Thyra github and downloads Thyra app based on the OS their using
2. User sees uploaded file on their computer 
3. User open the files by clicking on it
4. User see the icon tray installed 
5. User clicks on Massa icon and sees the following screen
<img width="398" alt="image" src="https://user-images.githubusercontent.com/109611779/209860970-e910b60a-99db-4e6a-8e43-4f065ed76248.png">

**How to**

- [ ] Update the existing icon tray design as described in the image above
- [ ] Note that the image is wireframe so it's approximative + it is inspired from apple design so try to match it (opacity, icon colours ...) see below
<img width="301" alt="image" src="https://user-images.githubusercontent.com/109611779/209861172-5dc1c8bd-2a02-44b6-952d-59c51326f25e.png">

**Comment by thomas-senechal** [comment]
It looks like Qt doesn't have a `switch` or `toggle`. The only way of doing it is to have a our own images as we already do. We could change those images to better ones tho.

About the separators, it's pretty easy to add using the [`QMenu.addSeparator()`](https://doc.qt.io/qtforpython/PySide6/QtWidgets/QMenu.html#PySide6.QtWidgets.PySide6.QtWidgets.QMenu.addSeparator). 

But for the kind of "section titles" such as "Direct Access", "Plugins" etc, I found [`QMenu.addSection`](https://doc.qt.io/qtforpython/PySide6/QtWidgets/QMenu.html#PySide6.QtWidgets.PySide6.QtWidgets.QMenu.addSection). The issue is that this function doesn't adds the text passed as parameter.

3rd comment of [this article](https://www.pythonguis.com/faq/how-to-show-qmenu-title/) shows a menu a bit like we'd like to do, using the `QMenu.addSection`, but it doesn't work. This comment also explains that using the `Fusion` style fixes the issue. But I tried to use it using `QApplication.setStyle("Fusion")` (as explained in the comment), and `QApplication.setStyle(QStyleFactory.create("Fusion"))` as shown in the documentation. But none of those worked. 

I found out that there are 3 available styles `['macOS', 'Windows', 'Fusion']`, but none of them changed anything to the style of the System Tray Menu.

**Comment by thomas-senechal** [comment]
Here is the best result I was able to achieve:
<img width="177" alt="image" src="https://user-images.githubusercontent.com/44696378/214581334-fad2205e-9903-4e74-9621-1fc661dfca91.png">

@SlnPons What do you think about that ?

**Comment by B-Naoufal** [comment]
> Here is the best result I was able to achieve: <img alt="image" width="177" src="https://user-images.githubusercontent.com/44696378/214581334-fad2205e-9903-4e74-9621-1fc661dfca91.png">
> 
> @SlnPons What do you think about that ?

@thomas-senechal you can try this tuto but if its not very  time consuming https://www.youtube.com/watch?v=NnJFi285s3M

**Comment by thomas-senechal** [comment]
> > Here is the best result I was able to achieve: <img alt="image" width="177" src="https://user-images.githubusercontent.com/44696378/214581334-fad2205e-9903-4e74-9621-1fc661dfca91.png">
> > @SlnPons What do you think about that ?
> 
> @thomas-senechal you can try this tuto but if its not very time consuming https://www.youtube.com/watch?v=NnJFi285s3M

I'm not sure making our own toggle button, which will be used only for MacOS, is a good idea. Especially since it's only to fix a style issue.
I mean, we could use it for Linux and Windows, but do we really want to have this toggle with a MacOS design in every platform ? And it might feel weird mixed Windows or Linux design with this MacOS like toggle.

**Comment by SlnPons** [comment]
@thomas-senechal the plugins section is linked to which plug-in manager please? 
On my side I can't see any plugin on the list even though I have the following ones installed: 


![Image](https://user-images.githubusercontent.com/109611779/218806957-48b31ab7-1c84-409e-8d35-17cd321b01ab.png)

**Comment by thomas-senechal** [comment]
> @thomas-senechal the plugins section is linked to which plug-in manager please? On my side I can't see any plugin on the list even though I have the following ones installed. It's not a blocker to put it in done, anyway. But I would like to know just in case :) Cheers
> 
> ![Image](https://user-images.githubusercontent.com/109611779/218806957-48b31ab7-1c84-409e-8d35-17cd321b01ab.png)

Hi ! As explained [here](https://github.com/massalabs/Thyra-Menu-Bar-App/pull/33#issue-1572843274), the list of installed plugins isn't available for now.
